a=float(input("Enter First Number: "))
b=float(input("Enter Second Number: "))
c="Saurish"
print(a+b)
print(a*b)
print(c[0:4])
i = ["tom","harry","emma","india","yash"]
i.append("universe")
print(i)
print(i.count("harry"))
print(i.index("india"))
i.insert(2, "nepal")
print(i)
print(i.pop())
print(i)
i.reverse()
print(i)
i.remove("emma")
print(i)
